plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - Research Experience.md
remote_theme: pages-themes/leap-day@v0.2.0
title: Kyle Watson''s Research Experience
description: A portfolio of my projects
